---
site: "bookdown::bookdown_site"
documentclass: "book"
output:
  bookdown::bs4_book: "default"
---

# Design Theory
## Functional Dependencies (FD)
FDs are great for data storage and queries.  It allows for compression of data and optimization of queries.  FDs is the theory that allows us to decompose data and is the generalization of keys!

* FDs are denoted as $X \rightarrow Y$, read "_$X$ functionally determines $Y$_"
* $X$ and $Y$ are subsets of attributes in a relation $R$
* We say that $X\rightarrow Y$ if and only if any two tuples with the same value for $X$, also have the same value for $Y$ for any relation instance of $R$
* In practice, its common for the attributes in the right side of the FD to be singletons, that is $Y$ is a single attribute


## Keys of Relations
__Key__: Given a set of attributes for a relation $R$,  a set of attributes $K = \{ k_{1}, k_{2}, ... k_{n}\}$  such that $K \subseteq D$ is considered a key for R if it creates a FD for all attributes in $D - K$ and no subset of $K$ is a also a key (no subset creates FD for all attributes not in the subset).

__Superkey__:  Any set of attributes $K = \{ k_{1}, k_{2}, ... k_{n}\}$ is a superkey if $K$ creates a FD for all attributes in $D - K$ and a subset of of $K$ also creates a FD for all attributes no in the subset.

The above definitions imply that all keys are superkeys, but not all superkeys are keys.


## FD Equivalencies
* Given two sets of FDs $S$ and $T$, we say that _$S$ follows  from $T$_ if and only if all relation instances that satisfy $T$ also satisfy $S$
* $S$ and $T$ are considered equal if and only if $S$ follows from $T$ and $T$ follows from $S$, that is all relation instances that satisfy $T$ also satisfy $S$ and vice versa!


## Rules of Functional Dependencies
### Splitting
We can split a FD $A_{1} A_{2} ... A_{n} \rightarrow B_{1} B_{2} ... B_{m}$ into an equivalent set of FDs by making the right side singletons, that is 

$$A_{1} A_{2} ... A_{n} \rightarrow B_{1}$$

$$ A_{1} A_{2} ... A_{n} \rightarrow B_{2}$$
$$...$$

$$A_{1} A_{2} ... A_{n} \rightarrow B_{m}$$

$$ \forall i \in \{1, 2, ..., m\}$$


### Combining
We can reconstruct a split as well! that is we can turn

$$A_{1} A_{2} ... A_{n} \rightarrow B_{1}$$

$$ A_{1} A_{2} ... A_{n} \rightarrow B_{2}$$
$$...$$

$$A_{1} A_{2} ... A_{n} \rightarrow B_{m}$$

$$ \forall i \in \{1, 2, ..., m\}$$

into 

$$A_{1} A_{2} ... A_{n} \rightarrow B_{1} B_{2} ... B_{m}$$

\

__NOTE__: You cannot split the left side of a FD!


### Trivial FD
We say a FD $A_{1} A_{2} ... A_{n} \rightarrow B_{1} B_{2} ... B_{m}$ is trivial if and only if 

 $$B_{1} B_{2} ... B_{m} \subseteq A_{1} A_{2} ... A_{n}$$
 
 
### Trivial Dependency Rule
 The FD $A_{1} A_{2} ... A_{n} \rightarrow B_{1} B_{2} ... B_{m}$ is equivalent to $A_{1} A_{2} ... A_{n} \rightarrow C_{1} C_{2} ... C_{k}$ if there exists $c_{i} \in C_{1} C_{2} ... C_{k}$ such that 
 
 $$c_{i} \in  B_{1} B_{2} ... B_{m} - A_{1} A_{2} ... A_{n}$$


### Augmentation
If $A_{1} A_{2} ... A_{n} \rightarrow B_{1} B_{2} ... B_{m}$ then 

$$A_{1} A_{2} ... A_{n} C_{1} C_{2} ... C_{k} \rightarrow B_{1} B_{2} ... B_{m} C_{1} C_{2} ... C_{k}$$



### Transitive Rule
If $A_{1} A_{2} ... A_{n} \rightarrow B_{1} B_{2} ... B_{k}$ and $B_{1} B_{2} ... B_{j} \rightarrow  C_{1} C_{2} ... C_{k}$, then 

$$A_{1} A_{2} ... A_{n} \rightarrow, C_{1} C_{2} ... C_{k}$$

If some $C_{i} = A_{i}$, by the trivial dependency rule, those $C_{i}$ may be omitted.  


## Closures
### Closure Definition
Let $A = \{A_{1}, A_{2}, ..., A_{n} \}$ be a set of attributes and $S = \{S_{1}, S_{2}, ..., S_{k} \}$ be a set of FDs satisfying $A$

The closure of $A$ under $S$ is the set of attributes $B$ such that 

1. $A \rightarrow B$
2.  Every relation that satisfies all FD in $S$ also satisfies $A \rightarrow B$ "_$A \rightarrow B$ follows from $S$"_, that is, all relation instances that satisfy $S$ also satisfy $A \rightarrow B$

We denote closures as $A^{+}$


### Closure Computation Algorithm
```
Inputs:
  A - Some set of attributes
  S - Some set of FDs
  
BEGIN

  Let C = A (C is the returned closure for A)
  Split FDs in S so that each FD is singleton on the right side
  
  For s in S:
    If s is of the form B ->> K such that B is contained in C and K is not in C
      Add K to C
    Else
      Do nothing
  
  return C

END
```

### Closures and Keys
Closures can be used to determine if a set of attributes $A = \{A_{1}, A_{2}, ..., A_{n}\}$ is a key or superkey

If $A^{+}$ functionally determines all attributes not in $A$, then $A$ is a superkey!

If $A^{+}$ functionally determines all attributes not in $A$ and there does not exist a subset of $A$ whos closure functionally determines all attributes not in the subset, then $A$ is a key!


### Basis for sets of FDs
Given a set of FDs $S$ for a relation $R$, any set of FDs $K$ that is equivalent to S (FDs in $S$ & $K$ satisfy the same relation instances) is a basis for $S$.

A basis is minimal if the follow is true:

1. All FDs for $K$ have singleton right sides
2. If a FD is removed from $K$, then $K$ is no longer a basis for $S$
  * Can be shown by finding the closure of the FD's left side to the other FDs in the set $S$
  * If right side of any FD in $S$ does not appear in the closure, then the two sets are not equivalent, i.e. do not hold for the same set of relations!
3. If at least one attribute is removed from the left side of a FD in $K$, then $K$ is no longer a basis for $S$
  * Can be shown by checking the closure of the FD where an attribute is dropped on the left side (Same logic follows for bullet points in 2.)


## Projections of FDs
### FD Projection Definition
Given a relation $R$, a set of FDs $S$ that satisfy $R$, and some project of $R$, $R_{1} := \pi_{L}(R)$ for some set of attributes $L$, the _projection of FDs $K$_ is a set of FDs that 

1. Follow from $S$ (Satisfy the same relations as $S$)
2. Involve only attributes in $R_{1}$ (creates a minimal basis for $S$ with only attributes in $R_{1}$)


### FD Projection Algorithm
```
Inputs:
  R - some relation
  R1 - some projection of R
  
Outputs:
  K - The set of FDs that satisfy R1 and are a minimal basis for FDs for R
  
BEGIN
Let T = Null (thius is your returned projection)
Let Pow(R1) be the powerset of R1's attributes (the set of subsets for R1's attributes)

For ele in Pow(R1)
  Compute the closure of ele
  
  For each FD in of the form X -> A s.t. X, A are in R1 and X, A are in the closure of ele
    Add FD to T

For each FD in T
  Check which FDs point to the same attribute and remove all of them except for one

Return T
END
```

The for loop that iterates over the projection $T$ ensures that $T$ is a minimal basis for the FDs of $R$ 


## Design of Relational Database Schema
There exists a series of "anomolies" that we want to avoid when designed a database.

1. Redundancy - When we unnecessarily repeat attributes to compensate for another attribute
2. Update Anomaly - When we update a value in a relation, but that update does not reflect all tuples
3. Deletion Anomaly - If we delete a tuple, are we effectivly removing information for other attributes?

Relation Decomposition allows us to avoid anomalies.


## Boyce-Codd Normal Form (BCNF)
### BCNF Definition
A relation $R$ is in BCNF if and only if all non-trivial FDs for $R$ have a superkey on the left hand side


### BCNF Decomposition Algorithm
When decomposing a relation to BCNF, the following is required

1. Each new decomposed relation is in BCNF
2. You can join the decomposed relations to reconstruct the original relation (Lossless join)

The BCNF Decomposition Algorithm allows for this!

```
Inputs:
  R0 - A relation
  S0 - The set of FDs for R0
  
Outputs:
  C - The collection of decomposed relations that are all in BCNF and can reconstruct R0

BEGIN
  Let R = R0
  Let S = S0
  Let C = Null
  If R is in BCNF
    return R
    
  Else
    Take any FD X -> Y in S that violates BCNF
    Compute the closure of the FD
    Let R1 = Closure of FD
    Let R2 = be the union of X + any attribute not in the closure of FD
    Compute the projection of FDs from R onto R1 and R2
    
    If either R1 or R2 is in BCNF
      Add them to C
      
    Else
      recurse the algorithm with the violating relation and its FDs
  
  return C
END
```

### Pros & Cons of BCNF Decomposition
When executing BCNF decomposition, we wan to achieve the following

1. Elimination of anomalies 
2. Recoverability of information - Can we create the original relation with the decomposed relations?
3. Dependency Preservation - When reconstructing the original relation, can we satisfy its original FDs?

BCNF guarantees FDs from the original relation project onto the decomposed relations, meaning (2) is guranteed.


## Chase Test For Indentifying Lossless Joins
### Definitions
__Lossless Join:__ When we join all decomposed relations and reconstruct the original relation, this is known as a lossless join (no information was lost).

__Chase Test:__ The chase test uses the set of FDs for a relation $R$ to determine if a row, $t$, exists in $R$ and in the natural of of $R$'s decomposed relations, $\pi_{S1}(R) \bowtie \pi_{S2}(R) \bowtie ... \bowtie \pi_{Sk}(R)$.

The chase test determines if our decomposition creates a lossless join!!!

__Tableau:__  A tableau describes the decomposed relations into one table.  It's used in the chase test to determine lossless joins.

We will now show how to do a chase test via example:

Suppose we have $R(A, B, C, D)$ and decomposed relations $S_{1} = \pi_{AD}(R)$, $S_{2} = \pi_{AC}(R)$ and $S_{3} = \pi_{BCD}(R)$

The tableau for $R$ and its decompositions is

| Decomposition | $A$ | $B$ | $C$ | $D$ |
|:----:|:----:|:----:|:----:|:----:|
|$S_{1}$|$a$|$b_{1}$|$c_{1}$|$d$|
|$S_{2}$|$a$|$b_{2}$|$c$|$d_{2}$|
|$S_{3}$|$a_{3}$|$b$|$c$|$d$|

Each row represents a decomposed relation!  If an attribute is not in a decomposed relation, we give it a subscript for its row index.

Our goal is to use the FDs of $R$ to remove subscripts to obtain a row with no subscripts.  A row with no subscripts indicates the natural joins of each decomposition $S_{i}$ creates a row $t \in R$.  If we obtain $t$, then we have proven that the decomposition of $R$ has a lossless join!

If a FD defines the equivalency of components that have one instance unsubscripted and the others subscripted, make them all unsubscripted

If a FD defines the equivalency of components where all instances have subscripts, make them all have the same subscript


### Chase Test Example 
Suppose we have a relation with functional dependencies

$$R(A, B, C, D)$$

$$A \rightarrow B \qquad B \rightarrow C \qquad CD \rightarrow A  \qquad A \rightarrow C \text{ Transitive property}$$

$R$ has the following decompositions

$$S_{1} = \pi_{AD}(R) \qquad S_{2} = \pi_{AC}(R) \qquad S_{3} = \pi_{BCD}(R)$$

Then the tableau of this decomposition is as follows 

| Decomposition | $A$ | $B$ | $C$ | $D$ |
|:----:|:----:|:----:|:----:|:----:|
|$S_{1}$|$a$|$b_{1}$|$c_{1}$|$d$|
|$S_{2}$|$a$|$b_{2}$|$c$|$d_{2}$|
|$S_{3}$|$a_{3}$|$b$|$c$|$d$|

Since $A \rightarrow C$, when $a = a$, then $c = c$, therefore $c_{1} = c$.  We can rewrite the tableau as follows

| Decomposition | $A$ | $B$ | $C$ | $D$ |
|:----:|:----:|:----:|:----:|:----:|
|$S_{1}$|$a$|$b_{1}$|$c$|$d$|
|$S_{2}$|$a$|$b_{2}$|$c$|$d_{2}$|
|$S_{3}$|$a_{3}$|$b$|$c$|$d$|

Now since $A \rightarrow B$, when $a = a$, $b = b$.  This means that $b_{1} = b_{2}$ and can rewrite them to both be either $b_{1}$ or $b_{2}$.

| Decomposition | $A$ | $B$ | $C$ | $D$ |
|:----:|:----:|:----:|:----:|:----:|
|$S_{1}$|$a$|$b_{1}$|$c$|$d$|
|$S_{2}$|$a$|$b_{1}$|$c$|$d_{2}$|
|$S_{3}$|$a_{3}$|$b$|$c$|$d$|

Finally since $CD \rightarrow A$, when $cd = cd$, $a = a$, so we can rewrite the table as follows

| Decomposition | $A$ | $B$ | $C$ | $D$ |
|:----:|:----:|:----:|:----:|:----:|
|$S_{1}$|$a$|$b_{1}$|$c$|$d$|
|$S_{2}$|$a$|$b_{2}$|$c$|$d_{2}$|
|$S_{3}$|$a$|$b$|$c$|$d$|

The row for $S_{3}$ shows no subscripts, therefore the chase test proves that the decomposition is lossless!

The chase test proves the existence of a tuple in original relation was constructed with the join of its decompositions.  If at least one tuple is constructed from the join, then we know that they all were constructed!


### Dependency Preservation
If a decomposition of a relation breaks a FD of the original relation, the FDs of the original relation do not hold!  In other words, the FDs for some decomposed relation does not create a basis for the FDs of the original relation, leading to not preserving dependencies during decomposition.


## Third Normal Form (3NF)
A table $R$ is in 3NF if one of the the thwo things hold true for every FD of $R$

1. If all attributes in the right side of FD is prime, i.e.  the attribute is a member of some key.
2.the left side is a super key